volumes:
  pgdata:
  adcm:

networks:
  arenadata:
    name: arenadata

services:
  adcm:
    image: "hub.arenadata.io/adcm/adcm:2.12.0"
    ports:
      - "8000:8000"
    volumes:
      - adcm:/adcm/data
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASS=Ws3iysiw
      - LOG_LEVEL=INFO
    container_name: adcm
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    networks:
      arenadata:

  postgres:
    image: "postgres:16.14"
    environment:
      POSTGRES_PASSWORD: Ws3iysiw
      PGDATA: /var/lib/postgresql/data/16
    volumes:
      - pgdata:/var/lib/postgresql/data/16
    container_name: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      arenadata:
